[theme]
base = "dark"
backgroundColor = "#080808"
secondaryBackgroundColor = "#0e0e0e"
textColor = "#e2e2e2"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
